spring:
  flyway:
    baseline-on-migrate: true

  h2:
    console:
      enabled: true
      path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:C:\Users\Dell\Downloads\Todo-App-master\Todo-App\todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8085

task.template.allowMultipleTasks: false
